# Site settings
title: Icaro Erasmo's blog
description: Linux, Java, Vue js, Angular e tudo mais sobre desenvolvimento.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://icaroerasmo.com" # the base hostname & protocol for your site e.g. https://willianjusten.com.br

# User settings
username: Icaro Erasmo
user_description: Desenvolvedor Fullstack da Companhia de Processamento de Dados do Estado da Bahia
user_title: Fullstack Developer
email: me@icaroerasmo.com
twitter_username: icaroerasmo
github_username:  icaroerasmo
linkedin_username:  icaroerasmo
disqus_username: icaroerasmo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
